namespace Bytecode;

public enum InstructionType
{
    PushInt,
    PushFloat,
    PushString,
    PushBool,
    Output,
    Halt,
    Add,
    Subtract,
    Multiply,
    Divide,
    Mod,
    UnaryMinus,
    DefineVariable,
    LoadVariable,
    StoreVariable,
    Input,
    EnterScope,
    ExitScope,
    StringLength,
    StringIndex,
    CompareEqual,
    CompareNotEqual,
    CompareLess,
    CompareGreater,
    CompareLessEqual,
    CompareGreaterEqual,
    LogicalNot,
    Jump,
    JumpIfFalse,
}